name: PR Checks

on: [pull_request]

jobs:
  build:
    name: Run tests & Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: run Pull Request Checks
        run: |
          yarn install
          yarn test --coverage
          yarn build
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
