name: Push Checks

on: [push]

jobs:
  build:
    name: Lint / Pretty
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: run Push Checks
        run: |
          yarn install
          yarn lint
          yarn test
          yarn build